# Generated by Django 3.0.7 on 2020-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
